<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function byCategory($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.category = :category')
            ->orderBy('p.id', 'DESC')
            ->setParameter('category', $id);

        return $qb->getQuery()->getResult();
    }


    /**
     * TODO: Upgrade to ES search later
     * @param $pattern
     * @return array
     */
    public function search($pattern)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.name like :pattern')
            ->orderBy('p.id', 'DESC')
            ->setParameter('pattern', $pattern);

        return $qb->getQuery()->getResult();
    }
}
